name: "Pull Request"
description: "Submit a pull request to improve or extend the show-file-tree package"
title: "[PR]: "
labels:
  - "pull-request"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your contribution 🎉
        Please fill in all **required sections** so reviewers can understand, reproduce, and safely merge your changes.

  - type: input
    id: summary
    attributes:
      label: "🔑 Summary (one line)"
      description: "Provide a short description of what this PR does."
      placeholder: "e.g., Add --top flag for showing top N files by size"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: "📦 Type of change"
      description: "Select the type that best describes your changes."
      options:
        - Bug fix
        - New feature
        - Data change
        - Model/Experiment
        - Documentation
        - Infrastructure/CI
        - Deployment
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivation / Business Context"
      description: "Why are these changes needed? What problem or use case do they solve?"
      placeholder: "Explain the problem, metric, or business value."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 Detailed Description of Changes"
      description: "List the main changes (files, modules, datasets, configs)."
      placeholder: |
        - Added cli flag `--top`
        - Updated tree_renderer.py to support table output
        - Modified tests/test_cli_basic.py
    validations:
      required: true

  - type: textarea
    id: data_changes
    attributes:
      label: "📊 Data Changes (if applicable)"
      description: "If you touched data, describe dataset, source, version, and processing."
      placeholder: |
        - Dataset: fixtures/sample_tree/
        - Source: synthetic test data
        - Change: added hidden files
    validations:
      required: false

  - type: textarea
    id: evaluation
    attributes:
      label: "📈 Evaluation / Metrics (if applicable)"
      description: "Provide before vs after metrics, benchmarks, or runtime comparisons."
      placeholder: |
        - Baseline: Tree build time 3.2s
        - New: Tree build time 2.1s (35% faster)
    validations:
      required: false

  - type: textarea
    id: reproducibility
    attributes:
      label: "🔄 Reproducibility Steps"
      description: "How can reviewers run and verify your changes locally?"
      placeholder: |
        1. `pip install -e .`
        2. Run `show-file-tree tests/fixtures/sample_tree --top 3`
        3. Compare output to README example
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: "🧪 Tests"
      description: "List new/updated tests and whether all CI checks are passing."
      placeholder: |
        - Added test_cli_top.py
        - All tests passing (CI ✅)
    validations:
      required: true

  - type: textarea
    id: docs
    attributes:
      label: "📚 Documentation Updates"
      description: "Link or describe updated docs, README, or usage examples."
      placeholder: "Updated docs/usage.md and README examples."
    validations:
      required: true

  - type: textarea
    id: deployment
    attributes:
      label: "🚀 Deployment / Rollout Plan (if applicable)"
      description: "Describe rollout strategy, monitoring, or rollback plan if this affects production."
      placeholder: "N/A (not a deployment change)."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ Checklist"
      description: "Confirm you completed the following before requesting review."
      options:
        - label: "Code follows project style/lint rules"
          required: true
        - label: "Tests added/updated and passing locally"
          required: true
        - label: "Data validation (if applicable) completed"
          required: false
        - label: "Docs/README/usage updated"
          required: true
        - label: "Artifacts/notes stored (if applicable)"
          required: false
        - label: "No sensitive/PII data introduced"
          required: true
